# Generated by Django 3.1.7 on 2021-04-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': '服装分类最大长度不超过100个字符~！'}, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper', models.CharField(error_messages={'max_length': '店主的昵称不能超过20个字符！'}, max_length=20)),
                ('name', models.CharField(error_messages={'max_length': '店铺名最大长度不超过20的字符！'}, max_length=20)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('thumbnail', models.URLField()),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('shop', models.CharField(error_messages={'max_length': '店铺名的最大长度不能超过2-个字符！'}, max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.clothcategory')),
            ],
            options={
                'db_table': 'clothes',
                'ordering': ['-pub_time', 'price'],
            },
        ),
    ]
