# Generated by Django 3.1.7 on 2021-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothes',
            table='clothes',
        ),
    ]
