# Generated by Django 3.1.7 on 2021-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='shop',
            field=models.CharField(error_messages={'max_length': '店铺名的最大长度不能超过2-个字符！'}, max_length=20, null=True),
        ),
    ]
