# Generated by Django 3.1.7 on 2021-05-01 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210429_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='shop',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'max_length': '店铺名的最大长度不能超过2-个字符！'}, max_length=20),
            preserve_default=False,
        ),
    ]
