# Generated by Django 3.1.7 on 2021-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_clothesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesorder',
            name='istype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
