# Generated by Django 3.1.7 on 2021-05-08 08:12

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210508_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesorder',
            name='id',
        ),
        migrations.AddField(
            model_name='clothesorder',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
