# Generated by Django 3.1.7 on 2021-04-29 11:46

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPhotoModel',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('img_url', models.URLField()),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-pub_time'],
            },
        ),
    ]
