# Generated by Django 3.1.7 on 2021-05-05 04:26

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
            ],
            options={
                'db_table': 'closet',
            },
        ),
        migrations.CreateModel(
            name='PersonalPhotoModel',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('img_url', models.URLField()),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-pub_time'],
            },
        ),
    ]
